kind: Service
apiVersion: v1
metadata:
  name: "fortune-app"
spec:
  selector:
    app: "fortune-app"
    secure: "enabled"
  ports:
    - protocol: "TCP"
      port: 443
      targetPort: 443
      nodePort: 31000
  type: NodePort
