apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
spec:
  selector:
    matchLabels:
      app: fortune
  replicas: 1
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
        - name: fortune
          image: "us-central1-docker.pkg.dev/qwiklabs-resources/spl-lab-apps/fortune-service:1.0.0"
          ports:
            - name: http
              containerPort: 8080
